name: deep-learning
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - matplotlib=3.3.4
  - mpi4py=3.0.3
  - numpy=1.19.2
  - pytorch=1.8.1
  - scipy=1.4.1
  - torchvision=0.9.1
  - requests=2.28.1
  - pandas=1.3.5
  - scikit-learn=1.0.2