import configparser
import argparse
import logging
import os
import warnings
import torch
from fl import FL

data_configs = [
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/ablation/acce_rgb/A30_B30_AB0_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/ablation/acce_rgb/A30_B30_AB0_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/ablation/rgb_depth/A30_B30_AB0_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/ablation/rgb_depth/A30_B30_AB0_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/ablation/acce_depth/A30_B30_AB0_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/ablation/acce_depth/A30_B30_AB0_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/acce_rgb/A30_B0_AB0_label_A_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/acce_rgb/A0_B10_AB30_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/acce_rgb/A0_B0_AB30_label_AB_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/acce_rgb/A0_B10_AB30_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/acce_rgb/A10_B10_AB30_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/acce_rgb/A10_B0_AB30_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/acce_rgb/A0_B0_AB30_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/acce_rgb/A10_B10_AB30_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/acce_rgb/A0_B0_AB30_label_AB_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/acce_rgb/A0_B0_AB30_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/acce_rgb/A0_B30_AB0_label_B_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/acce_rgb/A10_B0_AB30_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/rgb_depth/A30_B0_AB0_label_A_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/rgb_depth/A0_B10_AB30_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/rgb_depth/A0_B0_AB30_label_AB_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/rgb_depth/A0_B10_AB30_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/rgb_depth/A10_B10_AB30_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/rgb_depth/A10_B0_AB30_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/rgb_depth/A0_B0_AB30_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/rgb_depth/A10_B10_AB30_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/rgb_depth/A0_B0_AB30_label_AB_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/rgb_depth/A0_B0_AB30_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/rgb_depth/A0_B30_AB0_label_B_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/rgb_depth/A10_B0_AB30_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/acce_depth/A30_B0_AB0_label_A_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/acce_depth/A0_B10_AB30_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/acce_depth/A0_B0_AB30_label_AB_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/acce_depth/A0_B10_AB30_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/acce_depth/A10_B10_AB30_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/acce_depth/A10_B0_AB30_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/acce_depth/A0_B0_AB30_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/acce_depth/A10_B10_AB30_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/acce_depth/A0_B0_AB30_label_AB_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/acce_depth/A0_B0_AB30_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/acce_depth/A0_B30_AB0_label_B_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/ur_fall/split_ae/acce_depth/A10_B0_AB30_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/ablation/acce_gyro/A30_B30_AB0_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/ablation/acce_gyro/A30_B30_AB0_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/ablation/acce_mage/A30_B30_AB0_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/ablation/acce_mage/A30_B30_AB0_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/ablation/gyro_mage/A30_B30_AB0_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/ablation/gyro_mage/A30_B30_AB0_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/acce_gyro/A30_B0_AB0_label_A_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/acce_gyro/A0_B10_AB30_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/acce_gyro/A0_B0_AB30_label_AB_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/acce_gyro/A0_B10_AB30_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/acce_gyro/A10_B10_AB30_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/acce_gyro/A10_B0_AB30_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/acce_gyro/A0_B0_AB30_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/acce_gyro/A10_B10_AB30_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/acce_gyro/A0_B0_AB30_label_AB_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/acce_gyro/A0_B0_AB30_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/acce_gyro/A0_B30_AB0_label_B_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/acce_gyro/A10_B0_AB30_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/acce_mage/A30_B0_AB0_label_A_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/acce_mage/A0_B10_AB30_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/acce_mage/A0_B0_AB30_label_AB_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/acce_mage/A0_B10_AB30_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/acce_mage/A10_B10_AB30_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/acce_mage/A10_B0_AB30_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/acce_mage/A0_B0_AB30_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/acce_mage/A10_B10_AB30_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/acce_mage/A0_B0_AB30_label_AB_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/acce_mage/A0_B0_AB30_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/acce_mage/A0_B30_AB0_label_B_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/acce_mage/A10_B0_AB30_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/gyro_mage/A30_B0_AB0_label_A_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/gyro_mage/A0_B10_AB30_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/gyro_mage/A0_B0_AB30_label_AB_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/gyro_mage/A0_B10_AB30_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/gyro_mage/A10_B10_AB30_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/gyro_mage/A10_B0_AB30_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/gyro_mage/A0_B0_AB30_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/gyro_mage/A10_B10_AB30_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/gyro_mage/A0_B0_AB30_label_AB_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/gyro_mage/A0_B0_AB30_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/gyro_mage/A0_B30_AB0_label_B_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/mhealth/split_ae/gyro_mage/A10_B0_AB30_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/opp/dccae/A30_B0_AB0_label_A_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/opp/dccae/A0_B10_AB30_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/opp/dccae/A0_B0_AB30_label_AB_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/opp/dccae/A0_B10_AB30_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/opp/dccae/A10_B10_AB30_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/opp/dccae/A10_B0_AB30_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/opp/dccae/A0_B0_AB30_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/opp/dccae/A10_B10_AB30_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/opp/dccae/A0_B0_AB30_label_AB_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/opp/dccae/A0_B0_AB30_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/opp/dccae/A0_B30_AB0_label_B_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/opp/dccae/A10_B0_AB30_label_A_test_B',
    '/home/collin/Desktop/iotdi22-mmfl/config/opp/ablation/A30_B30_AB0_label_B_test_A',
    '/home/collin/Desktop/iotdi22-mmfl/config/opp/ablation/A30_B30_AB0_label_A_test_B'
]

def read_config(path):
    config = configparser.ConfigParser()
    config.read(path)

    return config

for path in data_configs:
    config = read_config(path)
    fl = FL(config)
    fl.start()